using System;

namespace OCC.Shared.Models
{
    /// <summary>
    /// Represents a mobile or desktop device registered to receive push notifications for a specific user.
    /// Maps a Push Token (FCM/APNs) to a system User ID.
    /// </summary>
    public class UserDevice : BaseEntity
    {
        /// <summary> The ID of the user who owns this device. </summary>
        public Guid UserId { get; set; }

        /// <summary> The unique push notification token generated by Firebase (FCM) or Apple (APNs). </summary>
        public string DeviceToken { get; set; } = string.Empty;

        /// <summary> The platform type (e.g., "Android", "iOS", "Windows"). </summary>
        public string Platform { get; set; } = "Unknown";

        /// <summary> Optional name for the device (e.g., "Samsung Tablet S9"). </summary>
        public string? DeviceName { get; set; }

        /// <summary> When this device was last seen/registered. </summary>
        public DateTime LastSeenUtc { get; set; } = DateTime.UtcNow;

        /// <summary> Navigation property to the owner. </summary>
        public virtual User? User { get; set; }
    }
}
